@extends('layouts.app')
@section('title', $shipment->shipment_number)
@section('page-title', __('shipments.shipments'))

@section('content')
@php($money = fn ($amount) => number_format((int) $amount).' '.__('ui.currency.syp'))
<x-page-header :title="$shipment->shipment_number" :description="$shipment->shipment_date?->format('Y-m-d')" :back="route('shipments.index')"><x-btn :href="route('shipments.edit', $shipment)" variant="secondary">{{ __('ui.actions.edit') }}</x-btn><x-btn :href="route('shipments.manifest', $shipment)" variant="secondary">{{ __('shipments.manifest') }}</x-btn></x-page-header>
<div class="grid gap-6 lg:grid-cols-3"><x-card :title="__('shipments.shipment')" class="lg:col-span-2"><dl class="grid gap-4 sm:grid-cols-3"><div><dt class="text-xs text-slate-500">{{ __('shipments.truck') }}</dt><dd class="font-bold">{{ $shipment->truck?->plate_number }}</dd></div><div><dt class="text-xs text-slate-500">{{ __('shipments.driver') }}</dt><dd class="font-bold">{{ $shipment->driver?->name }}</dd></div><div><dt class="text-xs text-slate-500">{{ __('ui.fields.status') }}</dt><dd><x-status-badge :status="$shipment->status" /></dd></div></dl></x-card><x-card :title="__('shipments.orders')"><p class="text-3xl font-black text-brand-700">{{ $shipment->orders->count() }}</p></x-card></div>
<x-card :title="__('shipments.orders')" class="mt-6"><div class="table-scroll"><table class="table"><thead><tr><th>{{ __('portal.order_number') }}</th><th>{{ __('ui.fields.customer') }}</th><th>{{ __('ui.fields.status') }}</th><th>{{ __('ui.fields.total') }}</th></tr></thead><tbody>@forelse($shipment->orders as $order)<tr><td><a class="font-bold text-brand-700" href="{{ route('orders.show', $order) }}">{{ $order->order_number }}</a></td><td>{{ $order->customer?->name }}</td><td><x-status-badge :status="$order->status" /></td><td>{{ $money($order->total_amount) }}</td></tr>@empty<tr><td colspan="4"><x-empty-state /></td></tr>@endforelse</tbody></table></div></x-card>
@if($readyOrders->isNotEmpty())<x-card :title="__('shipments.orders_attached')" class="mt-6"><form method="POST" action="{{ route('shipments.attach-orders', $shipment) }}" class="space-y-3">@csrf @foreach($readyOrders as $order)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="order_ids[]" value="{{ $order->id }}" class="rounded border-slate-300 text-brand-600"> {{ $order->order_number }} - {{ $order->customer?->name }}</label>@endforeach<x-btn type="submit">{{ __('ui.actions.save') }}</x-btn></form></x-card>@endif
@endsection
